### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by hotate1000** [hotate1000/chat-space20200303#11]
# IPアドレス
18.178.147.178

**Comment by miyu-yamamoto** [comment]
辻野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○ サイドバー内のグループ名と最新のメッセージの下に線が表示されている**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by hotate1000** [comment]
辻野です！ご確認頂きありがとうございます！

サイドバーの下線（aタグ）について、
サイドバーのHAMLにaタグ用のクラスを設定し、SCSSにtext-decoration: none;を設定しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
